version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-function-micronaut"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-kqzjbum3gdwu"
s3_prefix = "aws-function-micronaut"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
